services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend/logs:/app/logs

  nginx_frontend:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./backend/logs:/app/logs