version: '3.8'

services:
  backend:
    build: .
    container_name: dashboard_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: dashboard_db
    environment:
      POSTGRES_USER: gen_user
      POSTGRES_PASSWORD: agicQu5.d+)8{c
      POSTGRES_DB: default_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
